language: android
jdk: oraclejdk8
sudo: false
before_install:
- yes | sdkmanager "platforms;android-28"
before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
  - "$HOME/.gradle/daemon"
  - "$HOME/.gradle/native"
  - "$HOME/.android/build-cache"
env:
  global:
  - GRADLE_OPTS="-Xmx512m"
  - ADB_INSTALL_TIMEOUT=8
  - secure: Qk6F7w936HkeLGtmT3+yoMrwrfNsHal6PX+Ae3nxyshoVXtR+NyFj1Ww8knWCDiry+QPYHNDyJ3Q+ONNqBKHbBFPm+5vYJ1MTMWH4kueuibChuFvjymmp0Gx/pIgiFChJhgXBHg3dJv3Bh9wEdlMCsmCjQ0v0XKw/FnfsqeWrDAYMC7LPw4d/mYeJ1H0MkKMUtUfsAU0qIOIxwXvUMJcc+GDNaat05XtvgGHF9r3oHQOZ9LQuhe7qItRFF7PaJvFBIb6/YFrg4eMyiLw2BaMqAdFZ+cGOqapUfEZDq6iMjJH6OE65EG52M9/ZnZjlf5CqP73o83ht5XwyH63/01cVTZcaEMdsE90Mr15d0PkYy5hseXRiokcL9tmf1xjPZVKsca3+JZxxTQ77m996L08dj/UuQSMy+kPwh+ePWajnRv7ejq6eDNWBPRuCNiCiUMtr6Q5jN7aK/568EWwjcIBHs1tm4trsDbw5Qsw9j/sK6slFNuW0W/FBJH+ELU2Qw/gQZJ1XnZl6Ximkl3/MTTg8h+eoKtlqHooyxG0AphL2ahzkOgLuzZgNYAg8NV1AipBv0Wf5ykVngelCcwXSx4QlKec8oWE2lBuuujk8KHECjJNvGePRCO2OYKpHjEafSej/3d7mtSmnLjx3PuzIwc/b7C9SeFDH8Wp22iqT8J0RaI=
android:
  components:
  - tools
  - platform-tools
  - tools
  - build-tools-28.0.3
  - android-22
  - sys-img-armeabi-v7a-android-22
  - android-28
  - extra-android-m2repository
  - extra-android-m2repository
  - extra-google-m2repository
  - extra-android-support
script:
- "./scripts/cd_script.sh"
